import { Movie } from '../interfaces/movie.interface';

export const movie: Movie = {
  adult: false,
  backdrop_path: '/fPGeS6jgdLovQAKunNHX8l0avCy.jpg',
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 28, name: 'Action' },
    { id: 12, name: 'Adventure' },
    { id: 53, name: 'Thriller' },
    { id: 10752, name: 'War' },
  ],
  homepage: 'https://www.amazon.com/dp/B08VFD1Y3B',
  id: 567189,
  imdb_id: 'tt0499097',
  original_language: 'en',
  original_title: "Tom Clancy's Without Remorse",
  overview:
    'An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.',
  popularity: 359.439,
  poster_path: '/6GCOpT8QcNzup09TAMmvvk22LTR.jpg',
  production_companies: [
    {
      id: 4,
      logo_path: '/fycMZt242LVjagMByZOLUGbCvv3.png',
      name: 'Paramount',
      origin_country: 'US',
    },
    {
      id: 433,
      logo_path: null,
      name: 'Weed Road Pictures',
      origin_country: 'US',
    },
    {
      id: 82819,
      logo_path: '/5Z8WWr0Lf1tInVWwJsxPP0uMz9a.png',
      name: 'Skydance Media',
      origin_country: 'US',
    },
    {
      id: 51593,
      logo_path: null,
      name: 'Midnight Radio',
      origin_country: 'US',
    },
    {
      id: 102334,
      logo_path: '/espa8KYmHedu5p7GRrP9FFICLUp.png',
      name: 'Outlier Society Productions',
      origin_country: 'US',
    },
    {
      id: 114732,
      logo_path: '/tNCbisMxO5mX2X2bOQxHHQZVYnT.png',
      name: 'New Republic Pictures',
      origin_country: 'US',
    },
    {
      id: 20580,
      logo_path: '/tkFE81jJIqiFYPP8Tho57MXRQEx.png',
      name: 'Amazon Studios',
      origin_country: 'US',
    },
  ],
  production_countries: [
    { iso_3166_1: 'US', name: 'United States of America' },
  ],
  release_date: '2021-04-29',
  revenue: 0,
  runtime: 109,
  spoken_languages: [
    { english_name: 'English', iso_639_1: 'en', name: 'English' },
  ],
  status: 'Released',
  tagline: '',
  title: "Tom Clancy's Without Remorse",
  video: false,
  vote_average: 7.2,
  vote_count: 314,
};

export const newMovie: Movie = {
  adult: false,
  backdrop_path: '/vviYFL6bT0p2AkXI1WIKC2y0rRl.jpg',
  belongs_to_collection: null,
  budget: 0,
  genres: [{ id: 27, name: 'Horror' }],
  homepage: 'https://neonrated.com/films/in-the-earth',
  id: 748853,
  imdb_id: 'tt13429362',
  original_language: 'en',
  original_title: 'In the Earth',
  overview:
    'As a deadly virus ravages the world, Dr. Martin Lowery embarks on a mission to reach test site ATU327A, a research hub deep in the Arboreal Forest. The arduous journey, guided by park scout Alma, is set back by a nighttime attack that leaves the two bruised and shoeless. When they run into Zach, a man living off the grid, they gratefully accept his help. Zach’s intentions aren’t exactly what they seem, however, and a path out of the forest and into safety quickly fades as the line between myth and science blurs.',
  popularity: 11.13,
  poster_path: '/bUcWwnm2mHgllN4m95Xj8kSVyzp.jpg',
  production_companies: [
    {
      id: 90733,
      logo_path: '/3K9wCZTyDgop3ITK1rDi6T2PckE.png',
      name: 'Neon',
      origin_country: 'US',
    },
    {
      id: 16853,
      logo_path: '/f4OsvS3T5eNt7QvG2vJiOAIeS3B.png',
      name: 'Rook Films',
      origin_country: 'GB',
    },
  ],
  production_countries: [
    { iso_3166_1: 'GB', name: 'United Kingdom' },
    { iso_3166_1: 'US', name: 'United States of America' },
  ],
  release_date: '2021-04-30',
  revenue: 0,
  runtime: 107,
  spoken_languages: [
    { english_name: 'English', iso_639_1: 'en', name: 'English' },
  ],
  status: 'Released',
  tagline: 'Nature is a force of evil.',
  title: 'In the Earth',
  video: false,
  vote_average: 5.5,
  vote_count: 2,
};

export const sherlock: Movie = {
  adult: false,
  backdrop_path: '/veXdzn7LL0bFIDGmE7tTkvRg0qV.jpg',
  budget: 90000000,
  genres: [
    { id: 28, name: 'Action' },
    { id: 12, name: 'Adventure' },
    { id: 80, name: 'Crime' },
    { id: 9648, name: 'Mystery' },
  ],
  homepage: 'https://www.warnerbros.com/movies/sherlock-holmes/',
  id: 10528,
  imdb_id: 'tt0988045',
  original_language: 'en',
  original_title: 'Sherlock Holmes',
  overview:
    'Eccentric consulting detective, Sherlock Holmes and Doctor John Watson battle to bring down a new nemesis and unravel a deadly plot that could destroy England.',
  popularity: 29.394,
  poster_path: '/momkKuWburNTqKBF6ez7rvhYVhE.jpg',
  production_companies: [
    {
      id: 174,
      logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
      name: 'Warner Bros. Pictures',
      origin_country: 'US',
    },
    {
      id: 79,
      logo_path: '/tpFpsqbleCzEE2p5EgvUq6ozfCA.png',
      name: 'Village Roadshow Pictures',
      origin_country: 'US',
    },
    {
      id: 1885,
      logo_path: '/xlvoOZr4s1PygosrwZyolIFe5xs.png',
      name: 'Silver Pictures',
      origin_country: 'US',
    },
    {
      id: 23202,
      logo_path: null,
      name: 'Wigram Productions',
      origin_country: 'US',
    },
    {
      id: 19855,
      logo_path: null,
      name: 'Internationale Filmproduktion Blackbird Dritte',
      origin_country: '',
    },
  ],
  production_countries: [
    { iso_3166_1: 'AU', name: 'Australia' },
    { iso_3166_1: 'DE', name: 'Germany' },
    { iso_3166_1: 'GB', name: 'United Kingdom' },
    { iso_3166_1: 'US', name: 'United States of America' },
  ],
  release_date: '2009-12-23',
  revenue: 524028679,
  runtime: 129,
  spoken_languages: [
    { english_name: 'English', iso_639_1: 'en', name: 'English' },
    { english_name: 'French', iso_639_1: 'fr', name: 'Français' },
  ],
  status: 'Released',
  tagline: 'Nothing escapes him.',
  title: 'Sherlock Holmes',
  video: false,
  vote_average: 7.2,
  vote_count: 11320,
};
